// Code generated by "stringer -type=CardColor"; DO NOT EDIT.

package game

import "strconv"

const _CardColor_name = "WHITEBLACK"

var _CardColor_index = [...]uint8{0, 5, 10}

func (i CardColor) String() string {
	if i < 0 || i >= CardColor(len(_CardColor_index)-1) {
		return "CardColor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CardColor_name[_CardColor_index[i]:_CardColor_index[i+1]]
}
